### PR TITLE
Homekit, Trigger Interval, and Border Box Image Output

### PR DESCRIPTION
**Pull request by Ovaro**
Added support for Homekit, Trigger Interval, and Border Box Image Output (as per readme which you can merge or not - up to you).

### CODE REVIEW

**Comment by Christofo** [comment]
All of these changes sound great and I would love to merge them. I'm only seeing the changed README.md - can you commit the others?

**Comment by Ovaro** [comment]
Looks like I might have missed the changes you had in your latest code. Can you merge them in from this, or do you want me to merge those items?

**Comment by Christofo** [comment]
If you could merge them, it would be greatly appreciated!

**Comment by Ovaro** [comment]
OK- merged and tested now

**Comment by Christofo** [comment]
This is great - thank you very much for the contribution. I'm going to update the readme further and create a wiki soon.

**Comment by Ovaro** [comment]
Great! Loving how well this works in practice. My POE based system (Reolink) is slowly getting all the bells and whistles that Arlo/Netatmo, etc have. Let me know when you publish the new docker image. Cheers

**Comment by Christofo** [comment]
I'm using Reolink cameras with Surveillance Station, no complaints so far. Docker image has been updated. Thanks again!

**Pull request merged**
